# Generated by Django 5.0.6 on 2024-07-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='телеграмм-аккаунт'),
        ),
    ]
