# Generated by Django 5.0.6 on 2024-07-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'вознаграждение',
                'verbose_name_plural': 'вознаграждения',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='приятная привычка?')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичная привычка?')),
                ('activity', models.CharField(max_length=300, verbose_name='описание привычки')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время, в которое выполняется')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('duration', models.DurationField(default=None, verbose_name='Продолжительность действия в сек.')),
                ('periodicity', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в два дня', 'Раз в два дня'), ('Раз в три дня', 'Раз в три дня'), ('Раз в четыре дня', 'Раз в четыре дня'), ('Раз в пять дней', 'Раз в пять дней'), ('Раз в шесть дней', 'Раз в шесть дней'), ('Раз в неделю', 'Раз в неделю')], default='Раз в день', max_length=50, verbose_name='периодичность')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit', to='habits.habit', verbose_name='связанная привычка')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit', to='habits.reward', verbose_name='вознаграждение')),
            ],
            options={
                'verbose_name': ('привычка',),
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
