# Generated by Django 5.0.6 on 2024-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Продолжительность действия в сек.'),
        ),
    ]
