# Generated by Django 5.0.6 on 2024-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='время последнего выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='продолжительность действия в сек.'),
        ),
    ]
